version: '3'

services:
  windows-office:
    build:
      context: .
      args:
        - WORKDIR="C:\office-install"
        - OFFICE_DOWNLOAD_URL="https://download.microsoft.com/download/2/7/A/27AF1BE6-DD20-4CB4-B154-EBAB8A7D4A7E/officedeploymenttool_17531-20046.exe"
