version: "3"

services:
  windows-office:
    build:
      context: .
    restart: always
    volumes:
      - .\office-install:C:\office-install
      - .\test:C:\test
      - .\app:C:\app
    networks:
      - windows_office_network

networks:
  windows_office_network:
